version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: hackrx-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  ai-service:
    build: ./ai-service
    container_name: hackrx-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8000
      - HOST=0.0.0.0
    depends_on:
      - mongodb

  server:
    build: ./server
    container_name: hackrx-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/hackrx-chatbot?authSource=admin
      - AI_SERVICE_URL=http://ai-service:8000
      - CORS_ORIGIN=http://localhost:3000
      - NODE_ENV=production
    depends_on:
      - mongodb
      - ai-service

  client:
    build: ./client
    container_name: hackrx-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongodb_data:
